### ISSUE TITLE
Spin/hang after changing some settings

### ISSUE THREAD

**Issue by gojomo** [cxw42/TabFern#240] opened 2021-01-14 19:14 UTC
Was delighted to discover/try TabFern after growing concern with the orphaned/unmaintained status of TabsOutliner. 

Loaded into Brave, started poking around. After going to extension settings, I toggled a few options – IIRC, something about open-windows-to-top, and the 'skinny' scrollbars option. Went to reload TabFern window to see results (using menu 'View -< Reload this page", since `F5` did nothing) - and the TabFern window hung with its 'loading' animation, never fully refreshing, along with the tab where its settings were displayed. 

After a minute+, killed process in 'Task Manager' & tried restarting Brave. Hang in TabFern window recurred. 

Killed process, removed TabFern, restarted Brave, re-installed TabFern - Hang in TabFern window recurred. 

I suspect it's just a malfunction of one of the non-default options I set that's lingering - so, what's the best way to clear any residual non-default settings for a fresh-as-new re-install?

Thanks!

**Comment by cxw42** [comment] 2021-01-15 02:47
Thanks for reporting, and for the kind words!  I haven't tried TF on Brave.  Unfortunately, the easiest way to start fresh is to remove the extension and then re-add it.  On the plus side, TF by design backs up to disk, so you can uninstall any time without losing your information (at least as of the most recent backup).

If you are able to figure out which setting it is, would you please let me know?  That would certainly be worth fixing!  Thanks!

**Comment by gojomo** [comment] 2021-01-15 04:07
I did remove & re-add - and the problem recurred. So I think it's caching my settings changes. (Or, something else in its persistent state was the culprit.) Any idea where that any/all of that caching for TabFern is stored? 

(Totally separately: another cool get-control-of-tabs project recently on my radar is 'TabFS' - https://github.com/osnr/TabFS. Ultimately my hope is a workflow that clusters related tabs by site or topic, allows searching them by age/fuzzy-topic, & can auto-close/index unread tags for ambient resurfacing later when pursuing the same topics.)

**Comment by cxw42** [comment] 2021-01-17 03:07
That is odd!  It recurred after you re-added, but _without_ your changing the settings again?  Were you able to figure out exactly which settings?  Thanks!

Settings and tabs are both stored in the Chrome localStorage.  If you want to clear them manually, in TF, hit F12 for the developer console and then:
![image](https://user-images.githubusercontent.com/10515894/104829933-0b462200-5847-11eb-94df-71a83ce49250.png) 
Right-click the settings and hit Delete.  (Please note that I have not tested this :) .)

I'm happy to receive feature requests, or feel free to upvote already-open issues you find that you would be interested in.

**Comment by cxw42** [comment] 2021-01-17 03:39
Just tried skinny scrollbars with the latest dev version (e7dfd6d) and was not able to reproduce.  I did get an error message that I haven't seen before:

![image](https://user-images.githubusercontent.com/10515894/104830055-88be6200-5848-11eb-8639-fd7a7a427b6e.png)

That is fixed in new commit 35e081e.  Et voila:

![image](https://user-images.githubusercontent.com/10515894/104830295-87426900-584b-11eb-88d2-c58ab0f73791.png)

Are you able to try loading the latest unpacked?  If not, this change will be in the next release, coming in the next few weeks if all goes well.

**Comment by gojomo** [comment] 2021-01-18 19:42
First 5 rows of `about:version`:

```
Brave | 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)
-- | --
Revision | 9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f-refs/branch-heads/4280@{#2007}
OS | macOS Version 10.15.7 (Build 19H2)
JavaScript | V8 8.7.220.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
```

When I uninstall then re-install `TabFern`, this window pops up but then doesn't refresh for *minutes*, (including a popup of the "tab unresponsive - wait, kill?" dialog) which is what I had assumed was an endless spin: 
![image](https://user-images.githubusercontent.com/1641/104956379-dc33cb80-5980-11eb-8dba-dd165cd2fce8.png)

However, while composing this post as it spun, if *filly*na did briefly show another error (something about "installation not complete, 12/13, tabs won't be saved"), *then* finally refreshed again with actual content and no error! So it seems likely that what I've seen is just *extreme slowness* (upon 1st enablement or window-open?) rather than *permanent hang*. 

But also: I'm *not* seeing the Fern icon to the right of the address-bar, though other extensions' icons appear there fine. And thus after (just now) closing the TabFern window, I'm unsure how to open it again short of exiting & re-launching the browser. 

I'll keep poking around to see if I can narrow when the 'long unrefreshed spin' is triggered, & update with anything I notice.

**Comment by cxw42** [comment] 2021-01-19 02:10
Wow --- that is weird!  Yes, please keep me posted.

I tried the Web Store version (0.2.1) and was not able to reproduce.

![image](https://user-images.githubusercontent.com/10515894/104979166-9b17d780-59d1-11eb-8a64-2806f3fe57e5.png)

**Comment by gojomo** [comment] 2021-02-07 22:03
At this point, I'm not sure this wasn't just TabFern being really, really slow in some open/refresh/restart operations - because it hasn't recurred, but an operation like closing the last tab of a window – either in TabFern, or outside – causes it to busy-spin for ten seconds or more, sometimes popping the 'unresponsive - kill tab?' dialog. This might be unique to use in Brave, or with my humongous count of open tabs.

**Comment by cxw42** [comment] 2021-02-15 17:33
Having heard nothing more, I'm going to close this for now.  Feel free to reopen if you have more information!

**Closed** 2021-02-15 17:33 UTC
Labels: support, target-brave

**Comment by gojomo** [comment] 2021-02-18 18:04
Related, but not quite the same thing, is that many operations are so slow they lead to a 10sec+ freeze of the TabFern window, and pop the "unresponsive - kill tab?" dialog-box. Most notably: closing the last tab of a window (from *either* TabFern or the tab itself), and the TabFern "move to top" right-click menu operation. 

One of the main appeals of TabFern (like TabsOutliner before it) for me would be the ability to rapidly review & close older windows/tabs. So, these long pauses are a major impediment. 

As I suspect you'd have more reports if this were common in Chrome, I have a hunch this may be a Brave-specific slowdown. If there's anything I can do to help profile the potential cause more, perhaps in a new more-focused issue, let me know.
