### ISSUE TITLE
After closing and opening the TF list window issue

### ISSUE THREAD

**Issue by zlinux** [cxw42/TabFern#308] opened 2022-12-26 18:30 UTC
Hello and Merry Christmas,

After closing and then opening TF list window, 

The windows with any changes either by adding or removing tabs or changes in the URL of a tab that happened after closing the TF list window become Unsaved.

Thank you ...

**Comment by zlinux** [comment] 2022-12-26 18:45
I mean the currently open windows that gets any changes after closing the TF list window, become as Unsaved windows. They lost association with the Saved windows.

For example, if I have an open and saved window "Example1" with 2 tabs "foo" and "bar".

After I close the TF list window, and then add a third tab "jar" to it.

And then open the TF list window by clicking on the extension icon, the "foo", "bar" and "jar" tabs become under an Unsaved window. And the previously saved window stay that doesn't have "jar" stays in the saved list.

So after opening the TF list window by clicking on the icon, the list shows:

[-] Unsaved
---- foo
---- bar
---- jar
[-] Example1
---- foo
---- bar

Sorry for the too long explanation.  Just wanted to make sure to make it clear.

Best Regards

**Comment by cxw42** [comment] 2022-12-27 18:03
Thanks for using TF and for the detailed report!  Yes, that is the current behaviour of TF.  The TF window is what watches for changes to the tabs, so if the TF window is closed, TF can't keep track of those changes.  

This is a duplicate of #247, so I am going to close this issue.  Feel free to watch #247 for any updates!

**Closed by cxw42** 2022-12-27 18:03 UTC
