### ISSUE TITLE
images in README.md

### ISSUE THREAD

**Issue by Procyon-b** [cxw42/TabFern#213] opened 2020-05-05 15:44 UTC
The page is using https://raw.githubusercontent.com/cxw42/TabFern/gh-pages/screenshot.png
but the url is now https://raw.githubusercontent.com/cxw42/TabFern/gh-pages/assets/img/screenshot.png

Same for:
https://raw.githubusercontent.com/cxw42/TabFern/master/static/assets/fern128.png
available here:
https://raw.githubusercontent.com/cxw42/TabFern/gh-pages/assets/img/fern128.png
But not the same branch. You'll have to double-check.

**Comment by cxw42** [comment] 2020-12-25 01:46
Thanks for reporting!  I just realized this is a duplicate of #224 :)

**Closed by cxw42** 2020-12-25 01:46 UTC
Labels: documentation, visuals
