### ISSUE TITLE
#35 again - recent issue

### ISSUE THREAD

**Issue by philiprhoades** [cxw42/TabFern#199] opened 2020-01-07 09:49 UTC
Chris,

I saw on:

Open/close tab-by-tab · Issue #35 · cxw42/TabFern
https://github.com/cxw42/TabFern/issues/35

that this feature is now supposed to be on the Master fork but when I installed that opening one tab at a time still did not work for me so I went back to 0.21 to report this issue.

Recently - and I am not sure what might have caused it - opening the first tab in a window will work but trying to open second or more tabs, on some windows, will open a TF extension tab instead - see the attached screen captures for the progression - if it still doesn't make sense I can try and be more expansive.

I have done a backup and restore but this does not fix the problem.

Thanks for your continued work on this great extension!

Reagrds,
Phil.
![Screenshot_2020-01-07_20-10-12_TF-0](https://user-images.githubusercontent.com/1153703/71885814-3d7e6780-318f-11ea-81ee-cf03ee7b847a.png)
![Screenshot_2020-01-07_20-11-12_TF-1](https://user-images.githubusercontent.com/1153703/71885815-3d7e6780-318f-11ea-8249-ccf8f70db87c.png)
![Screenshot_2020-01-07_20-13-51_TF-2](https://user-images.githubusercontent.com/1153703/71885817-3d7e6780-318f-11ea-9b28-aea6bd07235a.png)

**Comment by cxw42** [comment] 2020-01-07 11:08
Yep - thanks for the confirmation!  Closing as duplicate of #198

**Closed by cxw42** 2020-01-07 11:08 UTC

**Comment by cxw42** [comment] 2020-01-07 11:10
I believe I'll be working on this starting next week (2019-01-12), for what it's worth.

**Comment by philiprhoades** [comment] 2020-01-07 12:24
Cool!

**Comment by philiprhoades** [comment] 2020-01-28 00:30
Chris,

How did you go?  Any progress?  Can I help debug or anything? - if you can point me to the right place I could step through code in the debugger and see what I can find?

Thanks,
Phil.

**Comment by cxw42** [comment] 2020-01-28 01:29
I'm sorry to say I haven't had a chance --- things have been busier than I expected.  I appreciate your offer of debugging assistance!  I know what the problem is, but getting a large enough block of time to work on it has been a challenge.  If you know any JavaScript developers, what I need most is another pair of hands on the coding!

I have blocked off some time on the calendar this weekend to work on it --- hopefully nothing will come up.  Thanks for your understanding!

Chris

**Comment by philiprhoades** [comment] 2020-01-28 01:41
Chris,

I do know someone actually - Michael is the son of an old friend of mine - unfortunately he is really busy but he might still be interested - I will contact him.  I do need to make some progress learning JS myself so if Michael is interested, I might try and co-operate with him a little to see if I can get more familiar . . 

Back soon . .

P.

**Comment by cxw42** [comment] 2020-03-22 16:28
I do need some front-end developer help with #201 - my workaround isn't ideal :) .

**Comment by philiprhoades** [comment] 2020-05-02 04:07
Michael didn't get back to me so I am assuming it was his (young person) unusbtle way of saying he was too busy with his own stuff . . unfortunately . .

**Comment by cxw42** [comment] 2020-05-02 14:26
Thanks for asking him - I appreciate your trying!
