### ISSUE TITLE
[Fixed in Vivaldi 3.0] Vivaldi sometimes doesn't have chrome APIs available

### ISSUE THREAD

**Issue by cxw42** [cxw42/TabFern#171] opened 2019-03-16 12:56 UTC
### Summary

Vivaldi has a [confirmed bug](https://forum.vivaldi.net/post/278441) (VB-50853).  I have opened a [Vivaldi.net forum thread](https://forum.vivaldi.net/topic/35531/chrome-apis-intermittently-unavailable-on-2-3-1440-61-x86).

Extension to load unpacked for testing: 
[vivaldi-0.2.0-pre.5.zip](https://github.com/cxw42/TabFern/files/2973974/vivaldi-0.2.0-pre.5.zip).  

### Details

Originally reported by @philiprhoades in #170.  Tested in Vivaldi 2.3.1440.61 (version details below).

app/win/container.js died after closing TF then clicking the toolbar button.  

    TabFern common.js loading
    container.js:4 TabFern: running app/win/container.js
    common.js:8 TabFern common.js loading
    common.js:119 Uncaught TypeError: Cannot read property 'getMessage' of undefined
        at common.js:119
    container.js:69 TabFern main.js onload

The line in question is `vendor/common.js:119`:

    var _T = chrome.i18n.getMessage;

**Edit** I added a workaround for i18n.  Then I got another error in container: `Uncaught TypeError: Cannot read property 'WINDOW_ID_NONE' of undefined`.  It was in `app/win/const.js:71`:

    NONE:  chrome.windows.WINDOW_ID_NONE,

This sometimes happens when initially loading or reloading the extension, and sometimes when reopening the window by clicking the toolbar button.

I did test after a failure, and was able to access `WINDOW_ID_NONE` in the developer console!  But after another failure, I reloaded with a breakpoint set, and was not able to access `chrome.windows`.

I tried bumping up the timeout for auto-load from 500ms to 1000ms on Vivaldi, but it still isn't
reliable.

### Version

    Vivaldi	2.3.1440.61 (Stable channel) (32-bit)
    Revision	2280481e163fe1c769ad046b453248ddb5bd477e-refs/heads/master@{#629885}
    OS	Windows
    JavaScript	V8 7.2.502.28
    Flash	32.0.0.156 C:\WINDOWS\SysWOW64\Macromed\Flash\pepflashplayer32_32_0_0_156.dll
    User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.122 Safari/537.36 Vivaldi/2.3.1440.61
    Command Line	"C:\Users\username\prog\Vivaldi\Application\vivaldi.exe" --vivaldi-standalone --flag-switches-begin --flag-switches-end --ppapi-flash-path="C:\WINDOWS\SysWOW64\Macromed\Flash\pepflashplayer32_32_0_0_156.dll" --disable-smooth-scrolling --save-page-as-mhtml
    Executable Path	C:\Users\username\prog\Vivaldi\Application\vivaldi.exe
    Profile Path	C:\Users\username\prog\Vivaldi\User Data\Default

Screenshot:

![Untitled](https://user-images.githubusercontent.com/10515894/54476745-456fb400-47d7-11e9-9d81-5e2fc40a3a5a.png)

**Comment by cxw42** [comment] 2019-03-27 12:21
Still a problem as of 

    Vivaldi   2.4.1488.35 (Stable channel) (32-bit)
    Revision  c7d5625347d0332219e7343210ac4e6ba2a74ca5

[Changelog](https://update.vivaldi.com/update/2.0/relnotes/2.4.1488.35.html) doesn't mention VB-50853, and I was able to reproduce (although it took more tries).

**Comment by cxw42** [comment] 2019-04-07 23:18
Still a problem as of 

    Vivaldi   2.4.1488.36 (Stable channel) (32-bit)
    Revision  223d751823ecd7930e28ffe5eedcad1671775f83

**Comment by philiprhoades** [comment] 2019-04-08 14:25
Chris,

I switched back to Chrome because I needed to catch up on a lot of stuff - is there anything you want me to test on Vivaldi at the moment?

Phil.

**Comment by cxw42** [comment] 2019-04-08 14:37
Nope - I just wanted to make sure you had the latest information.  Let me know if you do switch back to Vivaldi.  Otherwise, I'll check TF each time a Vivaldi update comes out.  Thanks!

**Comment by philiprhoades** [comment] 2019-04-08 14:48
Cool - thanks again!

**Comment by cxw42** [comment] 2020-04-26 21:54
I can no longer reproduce this bug in Vivaldi 3.0! \o/  If you have experience it, please try updating Vivaldi.  I will leave this issue open for a bit so folks have a chance to see the update, but other than that the issue is closed.

**Comment by philiprhoades** [comment] 2020-04-27 01:09
I eventually went back to Chrome so couldn't say if this is stil a problem . . if something has changed in Vivaldi and it is no longer a problem then closing the issue is good.

**Closed** 2020-04-30 12:06 UTC
Labels: blocked-by-upstream, infrastructure, target-vivaldi
