### ISSUE TITLE
Feature Request: Open Only Selected Tabs in a Window

### ISSUE THREAD

**Issue by cornell419** [cxw42/TabFern#295] opened 2022-08-22 08:01 UTC
Hi, TabFern Team. The extension works quite well for tab management, but it would be great if you could implement the ability to open specific/selected tabs in a previously saved window (please see attached screenshot), while the other tabs in the window would remain closed. I hope you could implement this feature, as it would help save memory by keeping unused tabs closed (but saved for later use). Kudos and thank you for the extension.
![tf-request](https://user-images.githubusercontent.com/111731890/185867558-e10bf848-11d4-416d-9dcd-8749b8e454db.png)

**Comment by cxw42** [comment] 2022-09-05 23:17
Thanks for using TF, and for your kind words!  Duplicate of #35, to be in the next release.

@cornell419 are you able to run git and npm?  If so, you can test this feature on branch `issue35rc`.

**Closed by cxw42** 2022-09-05 23:17 UTC
