### ISSUE TITLE
Option to import tabs and structure from Tabs Outliner (file import)

### ISSUE THREAD

**Issue by ShervinM** [cxw42/TabFern#99] opened 2017-12-16 03:38 UTC
Would be a good feature and an incentive for users to switch, if they could move their often huge list of tabs from TO. 
Not sure how much of a headache this one will be. alas this might be helpful
https://groups.google.com/forum/#!topic/tabs-outliner-support-group/eKubL9Iw230

"\databases\chrome-extension_eggkanocgddhmamlbiijnphhppkpkmkl_0" 
everything is here, in SQLite format but can be read in plain text as well. (comma separated)
URL, title, tree location array, favicon (honestly importing favicons is low priority), and bunch more that may not be as useful for import. you can import the file in SQLite or read plain in notepad++ or similar

**Comment by cxw42** [comment] 2017-12-17 15:27
Duplicate of #27 --- I completely agree with you!  I may be able to compile sqlite with emscripten and do it that way.  My preference is to have a converter plugin (once #26 is implemented), especially if I do wind up going with emscripten.  That will keep TF itself lighter.

**Comment by ShervinM** [comment] 2017-12-17 17:00
D'oh, should have searched before posting

btw, there is interest on firefox side for this extension as well. there was an attempt or two to make it but developers didn't see it through. I did link them here since you are the only developer actively working on any versions of this extension at this point. maybe you could do a firefox port at some point as well? :D 
We need faster development ;D (I haven't done any coding for years otherwise I would have helped out)

**Comment by cxw42** [comment] 2017-12-17 17:45
Indeed!  I looked into that before #82.  It's a lot easier than it used to be; Mozilla provides a shim to use the FF API for Chrome extensions.  The update to FF Quantum also killed some of the older FF extensions, from what I hear.

Unfortunately, may day job

**Comment by cxw42** [comment] 2017-12-17 17:45
Wrong button...

**Closed by cxw42** 2017-12-17 17:45 UTC
