### ISSUE TITLE
Syntax error in onTabReplaced()

### ISSUE THREAD

**Issue by Procyon-b** [cxw42/TabFern#304] opened 2022-12-20 21:51 UTC
### Item 1

In the final code, line 37839 of `main.js`, in the function `onTabReplaced()`
```
const errmsg = M.react_onTabReplaced(addedTabID, removedTabId);
```
`addedTabID` is undefined. It should be `addedTabId`

### Item 2

I'm running 2 instances of TF and the fixed version works correctly, but then I also see an error once on line 37847 where it tells me that `tab_val` is undefined. I've fixed it temporarily with a try-catch.

**Comment by cxw42** [comment] 2022-12-22 02:48
Thanks!  Would you please try branch `issue304` and confirm the issue is resolved?

**Comment by Procyon-b** [comment] 2022-12-22 17:07
I'm now running 0.3.1.1 in parallel. I'll know if it works properly in a few hours.

**Comment by Procyon-b** [comment] 2022-12-23 17:59
The fix works. I don't have orphaned tabs left in TF list.
But there is still the second error. I've launched chrome with TF 0.3.0 and 0.3.1.1 and looked at the dev tools. The I opened as many sites as needed to triggered a tabReplace. What I could see is that for every error in 0.3.0 I can see an error in 0.3.1.1

in 0.3.0
```
Error in event handler: ReferenceError: addedTabID is not defined
    at onTabReplaced (chrome-extension://oflhofndbpjhlfnkbclmfkchpnkghflg/win/main.js:37839:42)
```
in 0.3.1.1:
```
Error in event handler: ReferenceError: tab_val is not defined
    at onTabReplaced (chrome-extension://oflhofndbpjhlfnkbclmfkchpnkghflg/win/main.js:37844:75)
```

**Comment by cxw42** [comment] 2022-12-25 19:27
Sorry --- missed that second item when I read your initial report!  Fixed in force-pushed `issue304`, now 0.3.1.2.  Please let me know if the issue is fixed at 98e8924.  I tested the changes by manually invoking the `onTabReplaced()` function and it at least runs to completion :) .  Thanks!

**Comment by Procyon-b** [comment] 2022-12-25 20:08
I can confirm. Comparing side by side:
No more errors. No orphaned tabs in the list. Looks good.  :)

**Closed** 2022-12-25 22:05 UTC
Labels: bug, confirmed

**Comment by cxw42** [comment] 2022-12-25 22:24
@Procyon-b Much appreciated!  Will release shortly.

**Comment by cxw42** [comment] 2022-12-25 23:00
0.3.1 submitted for Google review --- will tag when it is released.

**Comment by Procyon-b** [comment] 2022-12-26 17:05
It's released.  :)
